name: Build for linux

on:
    pull_request:
        branches: [master]

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Building on latest version ubuntu
              run: |
                  echo "Building..."
                  sudo apt-get update -y
                  sudo apt-get install -y python3 python3-venv python3-pip
                  sudo ln -sf /usr/bin/python3 /usr/bin/python
                  python --version
                  pip --version
                  pip install pyinstaller
                  pyinstaller --onefile --name FLASH-OOU src/main.py
                  echo "App is builded!"
