name: CI - build and tests

on:
    pull_request:
        branches: [master]

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.11'
            - name: Install build dependencies
              run: |
                python -m pip install --upgrade pip
                pip install pyinstaller
            - name: Build executable
                run: |
                    pyinstaller --onefile --name FLASH-OOU src/main.py

    tests:
        name: Tests
        runs-on: ubuntu-latest
        needs: build
        steps:
            - uses: actions/checkout@v4
            - name: Setup Python
                uses: actions/setup-python@v4
                with:
                    python-version: '3.11'
            - name: Install test dependencies
                run: |
                    python -m pip install --upgrade pip
                    pip install pytest
            - name: Ensure a basic test exists (auto-generate if none)
                run: |
                    if [ ! -d tests ] || [ -z "$(ls -A tests 2>/dev/null || true)" ]; then
                        mkdir -p tests
                        cat > tests/test_basic.py <<'PYTEST'
def test_import_main():
        import importlib
        # simple smoke test: importing the main module should not raise
        importlib.import_module("src.main")
PYTEST
                    fi
            - name: Run tests
                run: pytest -q
